language: cpp

compiler:
    - clang

install:
    - sudo apt-get install libc++-dev
    - sudo apt-get install clang-3.8

# Don't use cmake build since travis has libc++ issues
script:
  - mkdir build
  - cd build
  - clang++-3.8 ../main.cpp -std=c++11 -o metaFloat
  - ./metaFloat
