language: cpp

compiler:
    - clang

install:
    - sudo apt-get install libc++-dev

# Don't use cmake build since travis has libc++ issues
script:
  - mkdir build
  - cd build
  - clang++ ../main.cpp -std=c++11 -o metaFloat
  - ./metaFloat
